site_name: Oferta Académica | UTPL
theme:
  name: material
  language: es
  palette:
    primary: custom 
    # Color amarillo para botones y enlaces
    accent: amber 
  features:
    - navigation.sections
    - content.tabs.link
    - content.code.copy

extra:
  design:
    color:
      primary: "#002D56"
      accent: "#F2A900"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
